// Generated by Calepin. Do not edit.

#let config = (
  enabled: true,
  results: path("results.json"),
  "image-meta": path("image-meta.json"),
  "source-dir": "components",
  source: "components/callout-boxes.typ",
  "raw-langs": ("d2", "dot", "mermaid", "python", "r", "tikz"),
)
