title = "Slydekit"
description = "Simple yet powerful presentation framework for Typst."
base_url = "https://maucejo.github.io/slydekit"
logo = "assets/slydekit-mini.svg"
logo_alt = "Slydekit logo"
theme = "./theme"
output-dir = "./_site"
pdf = false
typ = false
minify = true
search = "pagefind"
favicon = "assets/slydekit-icon.svg"
highlight-light = "assets/Catppuccin-Latte.tmTheme"

[executables]
typst = "typst"

[toc]
enabled = true
depth = 2
floating = true

[static]
include = ["assets/**"]

[menus]

  [[menus.main]]
  target = "./getting-started.typ"
  label = "Documentation"

  [[menus.social]]
  target = "https://github.com/maucejo/slydekit"
  label = "{icon:github}"
  aria-label = "GitHub"

[footer]

  [[footer.item]]
  label = "© 2026 Mathieu Aucejo"

  [[footer.item]]
  label = "Made with Calepin."
  target = "https://vincentarelbundock.github.io/calepin"

[sidebar]
fold = true

[[sidebar.section]]
  [[sidebar.section.item]]
  target = "./getting-started.typ"

[[sidebar.section]]
title = "Theming"
  [[sidebar.section.item]]
    target = "theming/built-in-themes.typ"

  [[sidebar.section.item]]
    target = "theming/fonts-colors.typ"

  [[sidebar.section.item]]
    target = "theming/custom-themes.typ"

[[sidebar.section]]
title = "Animations"
  [[sidebar.section.item]]
    target = "animations/anim.typ"

  [[sidebar.section.item]]
    target = "animations/pause.typ"

  [[sidebar.section.item]]
    target = "animations/item.typ"

  [[sidebar.section.item]]
    target = "animations/meanwhile.typ"

  [[sidebar.section.item]]
    target = "animations/alternatives.typ"

  [[sidebar.section.item]]
    target = "animations/draw-reveal.typ"

  [[sidebar.section.item]]
    target = "animations/code-reveal.typ"

[[sidebar.section]]
title = "Navigation, Progress"
  [[sidebar.section.item]]
    target = "navigation/topbar.typ"

  [[sidebar.section.item]]
    target = "navigation/outline.typ"

  [[sidebar.section.item]]
    target = "navigation/progress-bars.typ"

[[sidebar.section]]
title = "Components"

  [[sidebar.section.item]]
    target = "components/slides.typ"

  [[sidebar.section.item]]
    target = "components/appendix.typ"

  [[sidebar.section.item]]
    target = "components/localization.typ"

  [[sidebar.section.item]]
    target = "components/callout-boxes.typ"

  [[sidebar.section.item]]
    target = "components/handout.typ"

  [[sidebar.section.item]]
    target = "components/bibliography.typ"

  [[sidebar.section.item]]
    target = "components/miscellaneous.typ"
